package com.eiknat.lemmyclient.api.post.json

internal const val GET_POSTS_RESPONSE = """
{
  "posts": [
    {
      "id": 341,
      "name": "test post",
      "url": "",
      "body": "this is a post body",
      "creator_id": 345,
      "community_id": 2,
      "removed": false,
      "deleted": false,
      "locked": true,
      "stickied": true,
      "embed_title": null,
      "embed_description": null,
      "embed_html": null,
      "thumbnail_url": null,
      "ap_id": "https://test.org/post/341",
      "local": true,
      "nsfw": false,
      "banned": false,
      "banned_from_community": false,
      "published": "2020-06-08T20:20:08.276659",
      "updated": "2020-06-28T00:23:06.139958",
      "creator_actor_id": "https://test.org/u/testuser",
      "creator_local": true,
      "creator_name": "testuser",
      "creator_preferred_username": null,
      "creator_published": "2020-01-17T01:38:22.348392",
      "creator_avatar": "https://test.org/pictrs/image/img.jpg",
      "community_actor_id": "https://test.org/c/main",
      "community_local": true,
      "community_name": "main",
      "community_icon": "https://test.org/pictrs/image/img.png",
      "community_removed": false,
      "community_deleted": false,
      "community_nsfw": false,
      "number_of_comments": 82,
      "score": 63,
      "upvotes": 93,
      "downvotes": 30,
      "hot_rank": 0,
      "hot_rank_active": 0,
      "newest_activity_time": "2020-06-27T23:44:03.911130",
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "read": false,
      "saved": false,
      "duplicates": []
    },
    {
      "id": 532,
      "name": "sproink",
      "url": "https://test.org/index.html",
      "body": "content CONTENT CONTENT!",
      "creator_id": 435,
      "community_id": 2,
      "removed": false,
      "deleted": false,
      "locked": false,
      "stickied": true,
      "embed_title": null,
      "embed_description": null,
      "embed_html": null,
      "thumbnail_url": null,
      "ap_id": "https://test.org/post/532",
      "local": true,
      "nsfw": false,
      "banned": false,
      "banned_from_community": false,
      "published": "2020-03-03T14:31:27.209572",
      "updated": "2020-03-04T14:05:42.077381",
      "creator_actor_id": "https://test.org/u/testuser2",
      "creator_local": true,
      "creator_name": "testuser2",
      "creator_preferred_username": "testuser2",
      "creator_published": "2019-04-17T23:34:40.912940",
      "creator_avatar": "https://test.org/pictrs/image/img.jpg",
      "community_actor_id": "https://test.org/c/main",
      "community_local": true,
      "community_name": "main",
      "community_icon": "https://test.org/pictrs/image/img.png",
      "community_removed": false,
      "community_deleted": false,
      "community_nsfw": false,
      "number_of_comments": 38,
      "score": 76,
      "upvotes": 77,
      "downvotes": 1,
      "hot_rank": 0,
      "hot_rank_active": 0,
      "newest_activity_time": "2020-08-21T17:42:46.636261",
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "read": false,
      "saved": false,
      "duplicates": []
    }
  ]
}
"""