package com.eiknat.lemmyclient.api.post.json

internal const val POST_RESPONSE = """
{
  "post": {
    "id": 5146,
    "name": "test",
    "url": null,
    "body": null,
    "creator_id": 1201,
    "community_id": 2,
    "removed": false,
    "deleted": false,
    "locked": false,
    "stickied": false,
    "embed_title": null,
    "embed_description": null,
    "embed_html": null,
    "thumbnail_url": null,
    "ap_id": "https://test.org/post/5146",
    "local": true,
    "nsfw": false,
    "banned": false,
    "banned_from_community": false,
    "published": "2020-09-15T04:22:45.440842",
    "updated": null,
    "creator_actor_id": "https://test.org/u/eiknat1kt",
    "creator_local": true,
    "creator_name": "eiknat1kt",
    "creator_preferred_username": null,
    "creator_published": "2020-09-15T03:16:54.562601",
    "creator_avatar": null,
    "community_actor_id": "https://test.org/c/testcomm",
    "community_local": true,
    "community_name": "testcomm",
    "community_icon": null,
    "community_removed": false,
    "community_deleted": false,
    "community_nsfw": false,
    "number_of_comments": 0,
    "score": 0,
    "upvotes": 0,
    "downvotes": 0,
    "hot_rank": 1728,
    "hot_rank_active": 1728,
    "newest_activity_time": "2020-09-15T04:22:45.440842",
    "user_id": 1201,
    "my_vote": 1,
    "subscribed": true,
    "read": false,
    "saved": false,
    "duplicates": []
  }
}
"""