package com.eiknat.lemmyclient.api.comment.json

internal const val GET_COMMENTS_RESPONSE = """
{
  "comments": [
    {
      "id": 231,
      "creator_id": 34,
      "post_id": 211,
      "parent_id": 222,
      "content": "testing comments",
      "removed": false,
      "read": false,
      "published": "2020-09-10T09:12:04.020728",
      "updated": null,
      "deleted": false,
      "ap_id": "https://test.org/comment/32",
      "local": true,
      "community_id": 2,
      "community_actor_id": "https://test.org/c/announcements",
      "community_local": true,
      "community_name": "announcements",
      "banned": false,
      "banned_from_community": false,
      "creator_actor_id": "https://test.org/u/tester3",
      "creator_local": true,
      "creator_name": "tester3",
      "creator_avatar": "https://test.org/pictrs/image/1223.jpg",
      "score": 6,
      "upvotes": 6,
      "downvotes": 0,
      "hot_rank": 4,
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "saved": false
    },
    {
      "id": 17667,
      "creator_id": 10475,
      "post_id": 40282,
      "parent_id": null,
      "content": "Test.",
      "removed": false,
      "read": false,
      "published": "2020-09-10T04:46:18.125649",
      "updated": null,
      "deleted": false,
      "ap_id": "https://test.org/comment/17667",
      "local": true,
      "community_id": 2,
      "community_actor_id": "https://test.org/c/announcements",
      "community_local": true,
      "community_name": "announcements",
      "banned": false,
      "banned_from_community": false,
      "creator_actor_id": "https://test.org/u/tester",
      "creator_local": true,
      "creator_name": "tester",
      "creator_avatar": null,
      "score": 2,
      "upvotes": 2,
      "downvotes": 0,
      "hot_rank": 6,
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "saved": false
    }
  ]
}
"""