package com.eiknat.lemmyclient.api.user.json

internal const val USER_DETAILS_RESPONSE = """
{
  "user": {
    "id": 100,
    "actor_id": "https://test.org/u/testuser",
    "name": "testuser",
    "avatar": "https://test.org/pictrs/image/img.jpg",
    "email": "",
    "matrix_user_id": "@test:matrix.org",
    "bio": null,
    "local": true,
    "admin": true,
    "banned": false,
    "show_avatars": true,
    "send_notifications_to_email": false,
    "published": "2019-04-17T23:34:40.912940",
    "number_of_posts": 142,
    "post_score": 1496,
    "number_of_comments": 1277,
    "comment_score": 3940
  },
  "follows": [
    {
      "id": 16,
      "user_id": 100,
      "user_actor_id": "https://test.org/u/testuser",
      "user_local": true,
      "user_name": "testuser",
      "user_preferred_username": "testuser",
      "avatar": "https://test.org/pictrs/image/img.jpg",
      "community_id": 194,
      "community_actor_id": "https://test.org/c/testcomm1",
      "community_local": true,
      "community_name": "testcomm1",
      "community_icon": null,
      "published": "2019-04-25T14:37:40.232034"
    },
    {
      "id": 456,
      "user_id": 100,
      "user_actor_id": "https://test.org/u/testuser",
      "user_local": true,
      "user_name": "testuser",
      "user_preferred_username": "testuser",
      "avatar": "https://test.org/pictrs/image/img.jpg",
      "community_id": 130,
      "community_actor_id": "https://test.org/c/testcomm2",
      "community_local": true,
      "community_name": "testcomm2",
      "community_icon": null,
      "published": "2019-04-25T14:37:42.997355"
    }
  ],
  "moderates": [
    {
      "id": 142,
      "user_id": 100,
      "user_actor_id": "https://test.org/u/testuser",
      "user_local": true,
      "user_name": "testuser",
      "user_preferred_username": "testuser",
      "avatar": "https://test.org/pictrs/image/img.jpg",
      "community_id": 24,
      "community_actor_id": "https://test.org/c/testcomm3",
      "community_local": true,
      "community_name": "testcomm3",
      "community_icon": null,
      "published": "2019-04-25T16:44:20.017604"
    },
    {
      "id": 232,
      "user_id": 100,
      "user_actor_id": "https://test.org/u/testuser",
      "user_local": true,
      "user_name": "testuser",
      "user_preferred_username": "testuser",
      "avatar": "https://test.org/pictrs/image/img.jpg",
      "community_id": 45,
      "community_actor_id": "https://test.org/c/testcomm4",
      "community_local": true,
      "community_name": "testcomm4",
      "community_icon": null,
      "published": "2019-04-25T16:53:06.111327"
    }
  ],
  "comments": [
    {
      "id": 17838,
      "creator_id": 100,
      "post_id": 40333,
      "parent_id": null,
      "content": "",
      "removed": false,
      "read": true,
      "published": "2020-09-13T20:20:41.293115",
      "updated": null,
      "deleted": false,
      "ap_id": "https://test.org/comment/17838",
      "local": true,
      "community_id": 14929,
      "community_actor_id": "https://test.org/c/testcomm3",
      "community_local": true,
      "community_name": "testcomm3",
      "banned": false,
      "banned_from_community": false,
      "creator_actor_id": "https://test.org/u/testuser",
      "creator_local": true,
      "creator_name": "testuser",
      "creator_avatar": "https://test.org/pictrs/image/img.jpg",
      "score": 2,
      "upvotes": 3,
      "downvotes": 1,
      "hot_rank": 2,
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "saved": false
    },
    {
      "id": 443,
      "creator_id": 100,
      "post_id": 123,
      "parent_id": null,
      "content": "content goes h e r e",
      "removed": false,
      "read": true,
      "published": "2020-09-13T20:13:05.406104",
      "updated": null,
      "deleted": false,
      "ap_id": "https://test.org/comment/443",
      "local": true,
      "community_id": 14713,
      "community_actor_id": "https://test.org/c/testcomm5",
      "community_local": true,
      "community_name": "testcomm5",
      "banned": false,
      "banned_from_community": false,
      "creator_actor_id": "https://test.org/u/testuser",
      "creator_local": true,
      "creator_name": "testuser",
      "creator_avatar": "https://test.org/pictrs/image/img.jpg",
      "score": 2,
      "upvotes": 2,
      "downvotes": 0,
      "hot_rank": 5,
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "saved": false
    }
  ],
  "posts": [
    {
      "id": 432,
      "name": "test post.",
      "url": "https://test.org/index.html",
      "body": "test body",
      "creator_id": 100,
      "community_id": 2,
      "removed": false,
      "deleted": false,
      "locked": false,
      "stickied": false,
      "embed_title": "title",
      "embed_description": "desc",
      "embed_html": null,
      "thumbnail_url": "https://test.org/pictrs/image/img.png",
      "ap_id": "https://test.org/post/432",
      "local": true,
      "nsfw": false,
      "banned": false,
      "banned_from_community": false,
      "published": "2020-08-05T18:40:05.510680",
      "updated": null,
      "creator_actor_id": "https://test.org/u/testuser",
      "creator_local": true,
      "creator_name": "testuser",
      "creator_preferred_username": "testuser",
      "creator_published": "2019-04-17T23:34:40.912940",
      "creator_avatar": "https://test.org/pictrs/image/img.jpg",
      "community_actor_id": "https://test.org/c/testcomm7",
      "community_local": true,
      "community_name": "testcomm7",
      "community_icon": "https://test.org/pictrs/image/img.png",
      "community_removed": false,
      "community_deleted": false,
      "community_nsfw": false,
      "number_of_comments": 17,
      "score": 56,
      "upvotes": 56,
      "downvotes": 0,
      "hot_rank": 1,
      "hot_rank_active": 2,
      "newest_activity_time": "2020-08-07T01:08:19.076235",
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "read": false,
      "saved": false,
      "duplicates": []
    },
    {
      "id": 432432,
      "name": "testerino posterino",
      "url": "https://test.org/pictrs/image/img.png",
      "body": null,
      "creator_id": 100,
      "community_id": 343,
      "removed": false,
      "deleted": false,
      "locked": false,
      "stickied": false,
      "embed_title": null,
      "embed_description": null,
      "embed_html": null,
      "thumbnail_url": "https://test.org/pictrs/image/img.png",
      "ap_id": "https://test.org/post/432432",
      "local": true,
      "nsfw": false,
      "banned": false,
      "banned_from_community": false,
      "published": "2020-09-01T19:11:29.755498",
      "updated": "2020-09-01T19:11:52.925452",
      "creator_actor_id": "https://test.org/u/testuser",
      "creator_local": true,
      "creator_name": "testuser",
      "creator_preferred_username": "testuser",
      "creator_published": "2019-04-17T23:34:40.912940",
      "creator_avatar": "https://test.org/pictrs/image/img.jpg",
      "community_actor_id": "https://test.org/c/testcomm10",
      "community_local": true,
      "community_name": "testcomm10",
      "community_icon": null,
      "community_removed": false,
      "community_deleted": false,
      "community_nsfw": false,
      "number_of_comments": 5,
      "score": 22,
      "upvotes": 22,
      "downvotes": 0,
      "hot_rank": 1,
      "hot_rank_active": 1,
      "newest_activity_time": "2020-09-02T13:00:06.404460",
      "user_id": null,
      "my_vote": null,
      "subscribed": false,
      "read": false,
      "saved": false,
      "duplicates": []
    }
  ],
  "admins": []
}
"""
